# Generated by Django 3.1.6 on 2021-02-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptive_name', models.CharField(max_length=32, unique=True)),
                ('legal', models.IntegerField(choices=[(1, 'Deliverable'), (2, 'Ownership')], default=1)),
                ('unique', models.BooleanField(default=True)),
                ('website', models.CharField(max_length=512, unique=True)),
                ('expiry_date', models.DateTimeField()),
                ('underlying_value', models.TextField()),
            ],
        ),
    ]
