# Generated by Django 3.1.6 on 2021-02-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_contract_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
