# Generated by Django 3.1.6 on 2021-02-17 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_auto_20210217_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokertable',
            name='player_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to='poker.pokertableplayer'),
        ),
        migrations.AlterField(
            model_name='pokertable',
            name='player_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to='poker.pokertableplayer'),
        ),
    ]
