# Generated by Django 3.1.6 on 2021-02-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0004_auto_20210217_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='state',
            field=models.IntegerField(default=0),
        ),
    ]
