# Generated by Django 3.1.6 on 2021-02-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0005_pokertable_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='player_1_cards',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_2_cards',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
