# Generated by Django 3.1.6 on 2021-02-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0006_auto_20210218_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='deck',
            field=models.CharField(max_length=52, null=True),
        ),
    ]
