# Generated by Django 3.1.6 on 2021-02-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0007_pokertable_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='dealer',
            field=models.IntegerField(default=0),
        ),
    ]
