# Generated by Django 3.1.6 on 2021-02-18 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0008_pokertable_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='player_1_bet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_2_bet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
