# Generated by Django 3.1.6 on 2021-02-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0009_auto_20210218_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='blind',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=18),
        ),
    ]
