# Generated by Django 3.1.6 on 2021-02-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0011_auto_20210218_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokertable',
            name='player_1_cards',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='pokertable',
            name='player_2_cards',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
