# Generated by Django 3.1.6 on 2021-02-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0012_auto_20210219_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='player_1_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_2_money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='pot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18),
        ),
    ]
