# Generated by Django 3.1.6 on 2021-02-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0013_auto_20210220_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='board',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
