# Generated by Django 3.1.6 on 2021-02-27 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0014_pokertable_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='showDownCounter',
            field=models.DateTimeField(null=True),
        ),
    ]
