# Generated by Django 3.1.6 on 2021-03-11 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poker', '0015_pokertable_showdowncounter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokertable',
            old_name='showDownCounter',
            new_name='eventTimer',
        ),
        migrations.RemoveField(
            model_name='pokertable',
            name='player_1_bet',
        ),
        migrations.RemoveField(
            model_name='pokertable',
            name='player_2_bet',
        ),
        migrations.RemoveField(
            model_name='pokertable',
            name='pot',
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_0',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_0', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_0_action',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_0_cards',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_0_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_0_new_bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_0_prev_bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_1_action',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_1_new_bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_1_prev_bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_2_action',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_2_new_bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_2_prev_bet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='updateTimer',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pokertable',
            name='blind',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokertable',
            name='player_1_money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokertable',
            name='player_2_money',
            field=models.IntegerField(default=0),
        ),
    ]
