# Generated by Django 3.1.6 on 2021-03-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0016_auto_20210311_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokertable',
            name='player_0_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pokertable',
            name='player_1_action',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pokertable',
            name='player_2_action',
            field=models.BooleanField(default=False),
        ),
    ]
