# Generated by Django 3.1.6 on 2021-03-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0017_auto_20210312_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='log',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='pokertable',
            name='deck',
            field=models.CharField(max_length=104, null=True),
        ),
    ]
