# Generated by Django 3.1.6 on 2021-03-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0018_auto_20210313_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokertable',
            name='player_0_join',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_0_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_1_join',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_1_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_2_join',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokertable',
            name='player_2_leave',
            field=models.BooleanField(default=False),
        ),
    ]
