# Generated by Django 3.1.6 on 2021-02-07 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptive_name', models.CharField(max_length=32, unique=True)),
                ('legal', models.IntegerField(choices=[(1, 'Currency')], default=1)),
                ('unique', models.BooleanField(default=True)),
                ('expandable', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('website', models.CharField(max_length=512)),
                ('expiry_date', models.DateTimeField()),
                ('underlying_value', models.TextField()),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
