# Generated by Django 3.1.6 on 2021-02-08 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='underlying_value',
            new_name='details',
        ),
        migrations.AddField(
            model_name='contract',
            name='allow_fractions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contract',
            name='expandable',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=512)),
                ('email_verified', models.BooleanField(default=False)),
                ('website', models.CharField(max_length=512)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ownership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(choices=[(1, 'Currency')], default=1)),
                ('contract', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.contract')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='create_by', to=settings.AUTH_USER_MODEL)),
                ('owned_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
