# Generated by Django 3.1.6 on 2021-02-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210208_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='legal',
            field=models.CharField(choices=[('CURRENCY', 'CURRENCY'), ('SHARES', 'SHARES')], max_length=16),
        ),
        migrations.AlterField(
            model_name='ownership',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
