# Generated by Django 3.1.6 on 2021-02-24 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticker',
            old_name='creator',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='creator',
        ),
        migrations.AddField(
            model_name='ownership',
            name='holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holder', to=settings.AUTH_USER_MODEL),
        ),
    ]
