# Generated by Django 3.1.6 on 2021-04-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=50),
            preserve_default=False,
        ),
    ]
